name: coin_watcher
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  http_retry: ^0.1.1+3
  font_awesome_flutter: ^8.8.1
  modal_progress_hud: ^0.1.3
  intl: ^0.16.1
  deep_collection: ^0.1.5+1
  fl_chart: ^0.12.2
  crypto_font_icons: 0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

